dist: bionic
language: go
os: linux

branches:
  # blocklist
  except:
    # Avoid double testing stories which are tested as PRs.
    - /[a-zA-Z]+-\d+/
  # safelist
  only:
    # Allow testing changes to travis configuration.
    - /[a-zA-Z]+-\d+-travis-test/
    - /v[0-9]+.[0-9]+.[0-9]+/
    - master

services:
  - docker

go:
  - "1.15.x"

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME/protoc"
  - ln -s "$HOME/protoc/bin/protoc" "$HOME/bin"
  - go get -u github.com/golang/protobuf/protoc-gen-go

env:
  - PATH=$HOME/protoc/bin:$PATH

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "Nothing running since this is not a PR"; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/update-pr.sh; fi